#### 변수정의

In [8]:
a = 1; b = 2;

#### cell의 마지막 값만 보여준다.

In [9]:
a
b

2

In [17]:
a = 1; print(type(a))

<class 'int'>


In [10]:
a = 1.0; print(type(a))

<class 'float'>


In [18]:
a = 1; a = float(a); print(type(a))

<class 'float'>


In [13]:
a = 1.2; a = int(a); print(type(a)); print(float(int(a)))

<class 'int'>
1.0


#### float에 int를 쓰면 소수점자리 숫자들은 '버림'된다.

In [12]:
a = 1.6; a = int(a); print(a)

1


In [20]:
a = '123'; print(type(a)); print(a[1])

<class 'str'>
2


In [15]:
a=123; str(a)

'123'

In [21]:
a = '123'; a = list(a); print(type(a)); print(a); print(a[2])

<class 'list'>
['1', '2', '3']
3


In [17]:
a = [1,2,'hg']
b = [1,2,'ab',[4,5]]
print(b[-1][0])
print(b[-2][0])

4
a


#### 교훈: a[n][m] (n,m은 정수)는 a의 n자리에 있는 element가 list일 때만 가능하다.

In [19]:
a = [1,2,'hg']
print(a[-1][0])
print(a[-2][0])

h


TypeError: 'int' object is not subscriptable

#### string이나 list나 첫째 element의 자리 번호는 0.

In [22]:
a = [1,'2', [3, '4']]; print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'list'>
1
2
[3, '4']


#### 소괄호로 묶여 있는 것은 튜플, 대괄호로 묶여 있는 것은 리스트

In [23]:
a = (1,'2', [3, '4']); print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'tuple'>
1
2
[3, '4']


#### dictionary 형태
#### 표제어(앞부분)
#### index로 접근 하지 않교 표제어로 접근한다.


In [24]:
a =	{"a": "apple", "b": "orange", "c": 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


#### 튜플
#### 리스트와 비슷함
#### 리스트에 내용이 튜플 형태로 구성됨
#### 행렬과 생긴 것이 비슷하다.
#### a는 (2 * 3) 형태의 행렬과 비슷하게 생겼다.
#### 파이썬에는 행렬을 바로 사용할 수 있게 되어 있지 않아
#### 그래서 행렬을 쓸 수 있게 해주는 것이 필요 -> numpy

In [4]:
a=[(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

#### 파이썬에 여러 함수가 들어있지만, 그것을 파이썬에서 쓸 수 있는 것은 아님.
#### 가벼운 메모리 용량을 위해서 안에 들어있진 않고, package를 메모리로 불러오는 작업을 해야 한다.
#### import: 하드디스크에는 있지만 메모리에 올려져 있지 않은 package를 불러들이는(메모리에 올리는) 함수.
#### numpy는 python에 basic으로 들어와있지 않다.
#### 폴더가 하나 있는데, anaconda라는 디렉토리에 여러 폴더들이 있는데, 그 디렉토리를 메모리로 띄워라: import
#### 폴더에 numpy라는 것이 있다

#### as np는 type waste를 막기 위한 것
#### array는 행렬과 비슷하다.
#### b가 array화 된다.
#### 처음 import하는 데 시간이 좀 걸린다.
#### n dimensional array -행렬과 비슷하게 처리하는 것.

In [6]:
import numpy as np
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


#### numpy안에 있는 array함수를 사용한다.

In [5]:
import numpy
b = numpy.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


#### 행렬에서 b * b는 불가
#### array는 행렬이 아니라 행렬처럼 생김
#### 그냥 element까리 곱해짐.

In [29]:
print(b*b)

[[ 1  4  9]
 [ 9 64  0]]


#### numpy 안에 matrix함수가 있다
#### 이것을 쓰면 진짜 matrix가 된다

In [30]:
c = np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


#### 서로 모양이 맞지 않기 때문에 곱할 수 없다.

In [31]:
c*c

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

#### c.T: c의 transpose (transpose는 파이썬 꺼가 아니고 numpy 안에 있는 것)
#### 둘을 곱할 수 있다.
#### 곱한 결과는 당연히 matrix
#### python에서 가장 중요한 library: numpy(숫자적으로!)
#### class: 특정 함수와 특정 variable은 같이 묶여다닌다. (string은 곱하기 더하기 이런 거랑은 어울리지 않지) <- object oriented
#### python을 만든 사람: variable이 있으면 함수가 막 달려있다.
#### 지우긴 싫고 잠깐 숨기고 싶으면 output 부분을 더블클릭할 것.

In [32]:
c*c.T

matrix([[14, 19],
        [19, 73]])

## 이 둘의 차이가 이해가 잘 되지 않는다.

In [5]:
type(a)

list

In [6]:
print(type(a))

<class 'list'>
